@startuml
scale 480 width
state "Scheduling" as sch
state "Pre-Processing" as prep
state "Processing" as proc
state "Post-Processing" as post
state "Completed" as completed
state "Failed" as failed

[*] --> sch
sch --> prep: 5s success
sch --> failed: 5s failed
prep --> proc: 5s success
prep --> failed: 5s failed
proc --> post: 5s success
proc --> failed: 5s failed
post --> completed: 5s success
post --> failed: 5s failed
completed --> [*]
failed --> [*]

@enduml